version: 2.1
jobs:
    build:
      docker:
        - image: cimg/base:2022.06
          auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
        - checkout
        - run: |
                docker-compose -f docker-compose-build.yaml build --parallel
                docker tag udagram-api-user ${DOCKERHUB_USERNAME}/udagram-api-user:v6
                docker tag udagram-api-feed ${DOCKERHUB_USERNAME}/udagram-api-feed:v6
                docker tag udagram-frontend:local ${DOCKERHUB_USERNAME}/udagram-frontend:v6
                docker tag reverseproxy ${DOCKERHUB_USERNAME}/reverseproxy:v1
                echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” --password-stdin
                docker push ${DOCKERHUB_USERNAME}/udagram-api-user:v6
                docker push ${DOCKERHUB_USERNAME}/udagram-api-feed:v6
                docker push ${DOCKERHUB_USERNAME}/udagram-frontend:v6
                docker push ${DOCKERHUB_USERNAME}/reverseproxy:v1