version: 2.1
jobs:
    build:
      docker:
        - image: cimg/base:2022.06
          auth:
            username: bekakl
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
        - checkout
        - run: |
                docker-compose -f docker-compose-build.yaml build --parallel
                docker tag udagram-api-user bekakl/udagram-api-user:v6
                docker tag udagram-api-feed bekakl/udagram-api-feed:v6
                docker tag udagram-frontend:local bekakl/udagram-frontend:v6
                docker tag reverseproxy bekakl/reverseproxy:v1
                echo “$DOCKERHUB_PASSWORD” | docker login -u “bekakl” --password-stdin
                docker push bekakl/udagram-api-user:v6
                docker push bekakl/udagram-api-feed:v6
                docker push bekakl/udagram-frontend:v6
                docker push bekakl/reverseproxy:v1