version: 2.1
jobs:
    build:
      docker:
        - image: cimg/base:2022.06
          auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
        - checkout
        - run: |
                docker build -t udagram-api-feed ./udagram-api-feed
                docker tag udagram-api-feed bekakl/udagram-api-feed:v2
                docker build -t udagram-api-user ./udagram-api-user
                docker tag udagram-api-user bekakl/udagram-api-user:v2
                docker build -t udagram-frontend ./udagram-frontend
                docker tag udagram-frontend bekakl/udagram-frontend:v2
                docker build -t udagram-reverseproxy ./udagram-reverseproxy
                docker tag reverseproxy bekakl/reverseproxy:v2               
                docker tag reverseproxy bekakl/reverseproxy:v2
                docker login -u bekakl -p $DOCKERHUB_PASSWORD
                docker push bekakl/udagram-api-user:v2
                docker push bekakl/udagram-api-feed:v2
                docker push bekakl/udagram-frontend:v2
                docker push bekakl/reverseproxy:v2